---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	classify(classify)
	store_knowledge(store_knowledge)
	generate_teach_response(generate_teach_response)
	retrieve_context(retrieve_context)
	react_loop(react_loop)
	generate_solve_response(generate_solve_response)
	__end__([<p>__end__</p>]):::last
	__start__ --> classify;
	classify -. &nbsp;solve&nbsp; .-> retrieve_context;
	classify -. &nbsp;teach&nbsp; .-> store_knowledge;
	react_loop --> generate_solve_response;
	retrieve_context --> react_loop;
	store_knowledge --> generate_teach_response;
	generate_solve_response --> __end__;
	generate_teach_response --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
